#  Endterm Activity <hr style="border:2.5px solid #126782"></hr>

<b>Axel Nazir M. Belnas</b>
<br>3rd year

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'dataset\U.S._crude_oil_production_edit.csv', delimiter=',')

In [7]:
df.head()

,U.S. Crude Oil,Alabama,Alaska,Arkansas,Arizona,California,Colorado,Federal Offshore Gulf of Mexico Crude Oil,Federal Offshore Pacific Crude Oil,Florida,...,Ohio,Oklahoma,Pennsylvania,South Dakota,Wyoming,West Virginia,Virginia,Utah,Texas,Tennessee
0,5138,21,655,17,0,583,82,1326,67,5,...,14,186,8,5,144,6,0,60,1097,1
1,5177,21,640,17,0,586,81,1372,61,6,...,14,184,8,5,145,5,0,61,1111,1
2,5003,21,544,17,0,588,82,1272,70,5,...,14,188,8,5,145,6,0,62,1110,1
3,3974,21,681,16,0,587,88,242,67,5,...,14,186,8,5,144,6,0,63,1055,1
4,4738,21,716,17,0,586,86,803,66,6,...,14,185,8,5,145,6,0,64,1125,1

In [8]:
# storage of means
means_data = {col: [] for col in df.columns}

In [9]:
np.random.seed(42)
numeric_df = df.select_dtypes(include=np.number)

# sampling means
for i in range(50): # 50 times
    for c in df.columns:
        sample = np.random.choice(numeric_df[c], size=30, replace=True)
        means_data[c].append(np.mean(sample))

In [10]:
df_means = pd.DataFrame(means_data)
df_means

,U.S. Crude Oil,Alabama,Alaska,Arkansas,Arizona,California,Colorado,Federal Offshore Gulf of Mexico Crude Oil,Federal Offshore Pacific Crude Oil,Florida,...,Ohio,Oklahoma,Pennsylvania,South Dakota,Wyoming,West Virginia,Virginia,Utah,Texas,Tennessee
0,7548.500000,24.066667,564.133333,16.700000,0.0,538.600000,215.133333,1472.833333,42.300000,5.366667,...,36.700000,294.933333,12.533333,4.500000,170.633333,15.200000,0.0,85.400000,2468.000000,1.0
1,7600.133333,22.566667,552.900000,16.600000,0.0,532.633333,231.133333,1327.766667,46.400000,5.300000,...,25.233333,336.666667,13.666667,4.400000,184.400000,15.033333,0.0,84.800000,2617.100000,1.0
2,7175.200000,24.233333,544.333333,16.333333,0.0,544.066667,212.500000,1440.700000,45.600000,5.300000,...,30.466667,316.100000,13.400000,4.466667,174.866667,15.266667,0.0,82.133333,2644.600000,1.0
3,7177.266667,22.800000,560.033333,16.500000,0.0,533.566667,195.566667,1434.766667,44.300000,5.333333,...,35.166667,301.700000,13.166667,4.366667,168.400000,19.533333,0.0,84.800000,2526.966667,1.0
4,7729.133333,23.466667,546.566667,16.700000,0.0,540.866667,225.700000,1443.300000,46.966667,5.333333,...,33.266667,328.266667,13.000000,4.700000,174.833333,14.900000,0.0,83.633333,2616.466667,1.0
5,7548.366667,21.800000,524.466667,16.200000,0.0,533.566667,229.900000,1395.866667,43.033333,4.933333,...,31.700000,322.200000,14.666667,4.333333,174.666667,15.166667,0.0,86.733333,2556.566667,1.0
6,7093.566667,23.100000,537.133333,16.700000,0.0,535.733333,168.233333,1406.100000,44.600000,5.233333,...,30.600000,329.233333,15.400000,4.600000,187.833333,17.100000,0.0,81.400000,2125.666667,1.0
7,7394.533333,23.066667,533.300000,16.000000,0.0,540.966667,186.300000,1479.266667,46.300000,5.200000,...,28.266667,289.833333,13.433333,4.433333,174.133333,15.433333,0.0,87.200000,2380.333333,1.0
8,7441.000000,23.200000,546.766667,16.233333,0.0,534.366667,203.266667,1446.433333,44.166667,5.500000,...,33.500000,280.400000,14.966667,4.466667,182.166667,17.600000,0.0,83.166667,2337.433333,1.0
9,7343.933333,21.433333,560.300000,16.566667,0.0,529.666667,220.433333,1396.966667,47.233333,5.133333,...,30.266667,300.400000,15.366667,4.666667,174.566667,17.733333,0.0,86.900000,2475.433333,1.0
10,7207.066667,23.733333,525.533333,16.566667,0.0,525.633333,184.733333,1447.000000,44.733333,5.300000,...,31.066667,340.066667,13.400000,4.400000,191.233333,18.733333,0.0,87.266667,2069.500000,1.0
11,7452.333333,21.766667,534.733333,16.633333,0.0,535.766667,236.633333,1394.133333,41.300000,5.100000,...,33.166667,311.166667,14.866667,4.533333,183.833333,21.600000,0.0,88.066667,1885.266667,1.0
12,6946.900000,23.966667,546.833333,16.700000,0.0,536.866667,183.566667,1399.633333,41.566667,5.133333,...,34.500000,369.833333,14.100000,4.633333,187.700000,14.400000,0.0,86.366667,2552.466667,1.0
13,7612.266667,22.600000,521.700000,16.800000,0.0,544.533333,209.966667,1458.833333,37.800000,5.300000,...,30.666667,315.166667,14.833333,4.600000,180.700000,18.833333,0.0,87.800000,2542.133333,1.0
14,6906.133333,23.266667,531.100000,16.200000,0.0,527.333333,222.966667,1495.800000,40.366667,5.166667,...,31.733333,340.300000,13.300000,4.533333,177.066667,12.633333,0.0,80.100000,2300.200000,1.0
15,7862.066667,23.333333,522.133333,16.166667,0.0,539.700000,214.900000,1443.200000,39.433333,5.066667,...,30.866667,351.866667,13.333333,4.433333,188.566667,14.366667,0.0,77.000000,2348.866667,1.0
16,7432.233333,22.600000,534.300000,16.666667,0.0,538.533333,191.200000,1493.766667,41.200000,4.466667,...,31.266667,277.266667,14.266667,4.500000,175.466667,16.633333,0.0,84.533333,2061.300000,1.0
17,6924.433333,22.000000,534.766667,16.266667,0.0,536.133333,247.100000,1423.133333,46.166667,5.166667,...,38.833333,333.300000,14.400000,4.666667,183.466667,15.400000,0.0,88.333333,2494.033333,1.0
18,7430.500000,21.700000,517.733333,16.533333,0.0,547.066667,223.033333,1465.200000,39.766667,5.033333,...,39.000000,294.600000,12.966667,4.433333,179.300000,16.766667,0.0,91.633333,2093.133333,1.0
19,7726.233333,23.066667,552.566667,16.900000,0.0,537.400000,220.533333,1491.733333,39.666667,5.166667,...,34.266667,343.733333,13.033333,4.500000,183.433333,16.966667,0.0,84.000000,2265.733333,1.0
20,7279.700000,23.866667,567.633333,16.600000,0.0,540.233333,189.566667,1461.466667,42.066667,5.033333,...,27.833333,308.433333,13.933333,4.366667,174.333333,14.666667,0.0,84.033333,2428.966667,1.0
21,7059.600000,22.600000,550.633333,16.433333,0.0,539.500000,199.800000,1471.266667,42.466667,5.400000,...,27.966667,353.500000,13.266667,4.633333,188.233333,13.200000,0.0,82.933333,2145.400000,1.0
22,7504.166667,23.733333,561.800000,16.766667,0.0,525.066667,168.366667,1459.066667,38.933333,4.666667,...,32.300000,336.400000,13.600000,4.466667,176.233333,17.500000,0.0,88.166667,2444.566667,1.0
23,7389.533333,22.166667,536.433333,16.500000,0.0,536.433333,222.166667,1441.200000,41.966667,5.033333,...,30.333333,308.200000,14.066667,4.600000,174.266667,19.133333,0.0,85.900000,2649.400000,1.0
24,7763.433333,24.466667,544.166667,16.566667,0.0,529.866667,207.166667,1453.833333,42.166667,5.166667,...,34.533333,301.733333,14.200000,4.633333,183.833333,16.433333,0.0,86.300000,2587.166667,1.0
25,7363.733333,23.366667,550.300000,16.266667,0.0,544.100000,255.300000,1392.900000,41.966667,5.366667,...,34.966667,327.100000,14.733333,4.333333,183.933333,18.600000,0.0,90.066667,2616.066667,1.0
26,7968.100000,23.300000,542.166667,15.900000,0.0,527.533333,187.500000,1383.200000,35.333333,4.466667,...,36.800000,339.000000,13.800000,4.300000,173.200000,19.633333,0.0,86.966667,2532.966667,1.0
27,7612.700000,22.833333,540.666667,16.333333,0.0,539.000000,200.433333,1448.066667,39.133333,5.100000,...,32.233333,277.600000,13.433333,4.600000,181.700000,15.133333,0.0,90.100000,2213.633333,1.0
28,6981.466667,23.866667,544.400000,16.166667,0.0,533.100000,221.166667,1297.066667,46.800000,4.700000,...,37.300000,336.766667,14.366667,4.466667,171.566667,20.166667,0.0,83.700000,2340.566667,1.0
29,7001.666667,22.266667,514.366667,15.900000,0.0,537.966667,237.200000,1418.733333,38.033333,5.433333,...,32.800000,308.933333,13.100000,4.333333,178.966667,13.000000,0.0,84.833333,2316.300000,1.0
30,7863.300000,23.633333,552.266667,16.466667,0.0,538.833333,223.200000,1496.100000,41.866667,5.300000,...,34.633333,348.033333,13.733333,4.700000,186.700000,14.166667,0.0,82.666667,2303.933333,1.0
31,7355.566667,23.000000,527.233333,16.500000,0.0,540.500000,197.333333,1424.100000,38.766667,5.233333,...,33.133333,342.466667,14.300000,4.533333,176.766667,16.966667,0.0,82.500000,2388.133333,1.0
32,7478.200000,22.233333,553.700000,16.866667,0.0,526.866667,234.500000,1463.533333,40.800000,5.166667,...,28.333333,317.300000,13.300000,4.400000,203.733333,15.066667,0.0,81.633333,2334.033333,1.0
33,7480.533333,23.200000,543.466667,16.466667,0.0,527.333333,230.200000,1455.166667,40.566667,5.333333,...,35.100000,347.966667,13.300000,4.500000,186.766667,18.133333,0.0,84.833333,2444.966667,1.0
34,7010.766667,23.033333,520.900000,16.900000,0.0,524.266667,206.733333,1492.633333,41.833333,5.400000,...,34.533333,357.566667,13.766667,4.633333,178.666667,19.266667,0.0,89.033333,2753.666667,1.0
35,7084.900000,22.900000,556.033333,16.500000,0.0,532.266667,172.800000,1428.266667,48.166667,4.633333,...,33.933333,322.600000,12.400000,4.700000,168.133333,20.433333,0.0,86.000000,2613.933333,1.0
36,7231.966667,22.933333,552.066667,16.700000,0.0,543.900000,210.733333,1463.300000,44.900000,4.700000,...,36.566667,296.533333,12.600000,4.433333,185.133333,14.966667,0.0,87.400000,2724.066667,1.0
37,7373.100000,22.800000,565.266667,16.166667,0.0,530.166667,201.533333,1464.600000,40.900000,5.333333,...,37.800000,332.633333,13.433333,4.533333,170.433333,19.466667,0.0,81.666667,2410.666667,1.0
38,7720.966667,23.066667,542.966667,17.100000,0.0,535.100000,190.133333,1452.466667,41.133333,5.000000,...,37.700000,339.200000,13.000000,4.533333,182.100000,16.066667,0.0,82.400000,2312.366667,1.0
39,6720.733333,22.633333,524.933333,16.200000,0.0,541.500000,221.366667,1410.500000,47.666667,4.966667,...,23.233333,336.033333,13.366667,4.400000,180.633333,16.633333,0.0,80.300000,2330.933333,1.0
40,7339.366667,23.033333,534.700000,16.300000,0.0,534.366667,183.000000,1388.533333,45.466667,5.233333,...,30.933333,309.533333,14.666667,4.533333,187.366667,18.666667,0.0,91.000000,2339.833333,1.0
41,7103.466667,23.966667,551.566667,16.800000,0.0,533.266667,220.133333,1454.833333,45.266667,5.166667,...,35.733333,343.833333,14.333333,4.466667,177.600000,15.733333,0.0,88.333333,2409.300000,1.0
42,6935.333333,22.233333,525.733333,16.800000,0.0,545.600000,169.000000,1421.333333,37.800000,5.333333,...,32.666667,333.233333,13.600000,4.600000,177.233333,15.933333,0.0,80.966667,2334.866667,1.0
43,7475.433333,24.000000,535.300000,16.633333,0.0,533.200000,238.933333,1486.633333,42.733333,5.133333,...,31.966667,273.933333,14.466667,4.466667,179.666667,14.733333,0.0,90.866667,2290.033333,1.0
44,7904.766667,23.700000,560.500000,16.566667,0.0,537.766667,200.200000,1447.833333,45.300000,5.033333,...,38.100000,320.833333,14.566667,4.466667,179.333333,14.233333,0.0,84.833333,2603.833333,1.0
45,7772.500000,22.566667,504.433333,16.366667,0.0,534.266667,236.900000,1455.166667,40.266667,5.400000,...,29.433333,341.133333,14.233333,4.533333,176.800000,21.333333,0.0,85.700000,2601.833333,1.0
46,6590.000000,22.633333,541.466667,16.933333,0.0,537.700000,197.766667,1440.866667,41.266667,5.333333,...,33.600000,319.400000,12.733333,4.600000,179.900000,17.400000,0.0,84.433333,2323.233333,1.0
47,7603.866667,23.800000,543.566667,16.700000,0.0,526.033333,202.500000,1430.300000,42.100000,5.333333,...,36.666667,291.366667,14.133333,4.600000,190.133333,14.966667,0.0,84.366667,2377.133333,1.0
48,7403.066667,22.466667,572.433333,16.633333,0.0,550.733333,205.800000,1525.233333,43.766667,5.700000,...,32.700000,335.800000,14.200000,4.500000,185.666667,12.300000,0.0,85.200000,2310.500000,1.0
49,7148.633333,23.400000,544.066667,16.166667,0.0,544.233333,193.766667,1416.966667,40.733333,4.800000,...,29.000000,333.333333,13.633333,4.533333,184.733333,16.500000,0.0,83.266667,2346.033333,1.0

In [11]:
df_means.to_csv(r'dataset\dataset.csv', index=False)